### ISSUE TITLE
permissions for multierse sign portals

### ISSUE THREAD

**Issue by tryolivier** [Multiverse/Multiverse-SignPortals#41]
Hello

I use multiverse and multiversesign portals

I search the permissions to right click the sign to tp to the world

I want only the builder can be tp with the sign

What is the permissions ?

I search here but don't works : https://github.com/Multiverse/Multiverse-SignPortals/wiki/Big-list-o-permissions

thanks !

**Comment by caution3** [comment]
I am also having this problem.

**Comment by OpticFusion1** [comment]
Since i'm working on my own up to date fork, i'm adding this, from this point on if you run into an issue make an issue here https://github.com/OpticFusion1/Multiverse-SignPortals/ instead my fork of this plugin can be found here https://www.spigotmc.org/resources/multiverse-signportals-1-13-support.63881/

**Comment by OpticFusion1** [comment]
Since i'm working on my own up to date fork, i'm adding this, from this point on if you run into an issue make an issue here https://github.com/OpticFusion1/Multiverse-SignPortals/ instead my fork of this plugin can be found here https://www.spigotmc.org/resources/multiverse-signportals-1-13-support.63881/

**Comment by Jadiction** [comment]
Closing ticket because it's years old. In this case, you'd deny (or accept) permissions for the world for specific users/groups. This way when they click the signportal, it'll deny them when they do not have world access permission. If you need more assistance, you may receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
