### ISSUE TITLE
Nether sign portal starts players on fire

### ISSUE THREAD

**Issue by DracoZaroff** [Multiverse/Multiverse-SignPortals#42]
I'm not sure if this is normal and I can't seem to find a setting for it but when players use the nether portal with the sign on it they are set on fire upon teleporting.

**Comment by OpticFusion1** [comment]
If this is still an issue remake it here https://github.com/OpticFusion1/Multiverse-SignPortals/issues

**Comment by Jadiction** [comment]
Unable to replicate. It could be your TO portal's location that is on fire?
Closing ticket because it's years old & unable to be reproduced. Update to the latest versions of Multiverse (Core, Portals and any others you may use). Please open a new ticket if this issue persists or for a faster response, you can also receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
